"""P1 signup / local setup flow.

The public ``render_signup_flow`` function receives optional validation/save
callbacks, renders the split signup screen, and generates one local user setup
row only after the typed Anthropic API key validates.
"""
# --------------------------------------------------------------------------- #
# MODULE OVERVIEW — P1 SIGNUP / LOCAL ACCOUNT SETUP
# --------------------------------------------------------------------------- #
# Simple explanation:
# P1 is the first screen a new user sees. The left panel shows the Surf
# brand and tagline; the right panel is the "Welcome!" card where the
# user types a display name and an Anthropic API key. We validate the
# typed key against Anthropic, and only after that validation succeeds
# do we save the display name + key locally to SQLite.
#
# Authentication constraint (load-bearing):
# P1 is UNAUTHENTICATED. This module MUST NOT import or call the shared
# authenticated topbar (`app.brain.topbar.render_topbar`) — the Surf
# test suite explicitly enforces that. The authenticated topbar is only
# rendered on P2, P3, P6, and P7.
#
# Important code pieces:
# - `render_signup_flow`: the public entry point called by `views/signup.py`.
#   Accepts injectable `validate_key` / `save_setup` callbacks for tests.
# - `_save_after_validation`: gating function. Strips inputs, blocks
#   blanks, validates the key, then persists. Routes to `views/my_classes.py`
#   on success.
# - `_render_styles`: injects the page-scoped CSS (Surf colors, stamped
#   buttons, two-column layout).
# - `_render_left_panel` / `_render_setup_card`: the two visible halves
#   of the screen.
# - Embedded WOFF2 fonts: bundled fonts are inlined as data URIs because
#   Streamlit does not automatically serve files from `assets/fonts/`.
#
# App connection (privacy):
# The typed Anthropic API key is saved locally in plaintext SQLite on
# this user's computer. The visible disclaimer copy on the card tells
# the user that the key is validated with Anthropic, then saved on this
# computer.
# Renders signup and saves setup only after a typed Anthropic key validates.
from __future__ import annotations

# Imports split into four jobs: encode local fonts, type injected callbacks,
# escape user-facing HTML copy, and call Streamlit/database/key-validation APIs.
import base64
from collections.abc import Callable
from html import escape
from pathlib import Path

import streamlit as st

from app.brain.claude_client import validate_anthropic_key
from app.db.queries_users import upsert_user_setup

# User-facing copy and route constants feed the fields, buttons, toasts, and
# success navigation generated by ``_render_setup_card`` / ``_save_after_validation``.
CONSOLE_URL = "https://console.anthropic.com/"
PRIMARY_LABEL = "START SURFING >"
AI_USE_LABEL = "AI USE"

MONO_SUBTITLE = "SETUP YOUR ACCOUNT TO START SURFING THE CURVE"

# Helper copy is rendered below the button row after escaping, so the text can
# explain validation/local save without becoming executable HTML.
HELPER_COPY = "Clicking validates your Anthropic key with Anthropic, then saves your name and key to this computer."  # noqa: E501

MISSING_NAME_ERROR = "Add your display name to continue."
MISSING_KEY_ERROR = "Add your Anthropic API key to continue."

INVALID_KEY_TOAST = (
    "Invalid Anthropic key\n\n"
    "That key didn't validate. Double-check it on console.anthropic.com and try again."
)
SAVE_FAILURE_TOAST = (
    "Couldn't save your setup\n\n"
    "Something went wrong. Try again, or check your network."
)
SUCCESS_TOAST = "Saved."
VALIDATING_COPY = "Checking your Anthropic key…"

SWITCH_PAGE_PATH = "views/my_classes.py"

_AI_USE_COPY_PATH = Path(__file__).with_name("ai_use_copy.md")
_REPO_ROOT = Path(__file__).resolve().parents[3]
_FONTS_DIR = _REPO_ROOT / "assets" / "fonts"


# Receives no user data; generates Markdown for AI-use dialog copy.
def _load_ai_use_copy() -> str:
    return _AI_USE_COPY_PATH.read_text(encoding="utf-8")


# Receives a bundled font filename; generates a CSS data URI because Streamlit
# pages do not automatically serve files from ``assets/fonts``.
def _font_data_uri(filename: str) -> str:
    """Return a base64 data: URI for a font in ``assets/fonts/``.

    Embedding fonts inline avoids depending on Streamlit static file serving
    (and the ``app/static/...`` URL rewrites that come with it). The penalty is
    a one-time ~30KB CSS injection per page render, which is negligible.
    """
    # Keeps bundled fonts available without relying on static-file routes.
    encoded = base64.b64encode((_FONTS_DIR / filename).read_bytes()).decode("ascii")
    return f"data:font/woff2;base64,{encoded}"


# Builds the @font-face CSS block consumed by ``_render_styles``; if any font
# file is missing, it returns an empty block so the page still renders.
def _font_face_block() -> str:
    """Return @font-face CSS for the P1 hero and body fonts."""
    # Loads the exact font weights the signup screen uses.
    try:
        fraunces_regular = _font_data_uri("Fraunces-Regular.woff2")
        fraunces_medium = _font_data_uri("Fraunces-Medium.woff2")
        fraunces_black_italic = _font_data_uri("Fraunces-BlackItalic.woff2")
        fraunces_semibold_italic = _font_data_uri("Fraunces-SemiBoldItalic.woff2")
        mono_regular = _font_data_uri("JetBrainsMono-Regular.woff2")
        mono_medium = _font_data_uri("JetBrainsMono-Medium.woff2")
    except FileNotFoundError:
        # Missing bundled fonts should not block signup; system fonts are safer.
        return ""
    return f"""
    @font-face {{
      font-family: "Fraunces";
      src: url({fraunces_regular!r}) format("woff2");
      font-weight: 400;
      font-style: normal;
      font-display: swap;
    }}
    @font-face {{
      font-family: "Fraunces";
      src: url({fraunces_medium!r}) format("woff2");
      font-weight: 500;
      font-style: normal;
      font-display: swap;
    }}
    @font-face {{
      font-family: "Fraunces";
      src: url({fraunces_semibold_italic!r}) format("woff2");
      font-weight: 600;
      font-style: italic;
      font-display: swap;
    }}
    @font-face {{
      font-family: "Fraunces";
      src: url({fraunces_black_italic!r}) format("woff2");
      font-weight: 900;
      font-style: italic;
      font-display: swap;
    }}
    @font-face {{
      font-family: "JetBrains Mono";
      src: url({mono_regular!r}) format("woff2");
      font-weight: 400;
      font-style: normal;
      font-display: swap;
    }}
    @font-face {{
      font-family: "JetBrains Mono";
      src: url({mono_medium!r}) format("woff2");
      font-weight: 500;
      font-style: normal;
      font-display: swap;
    }}
    """


# Generates the page-scoped CSS: hidden Streamlit chrome, left brand panel,
# right setup panel, input styling, buttons, and reduced-motion fallback.
def _render_styles() -> None:
    st.html(
        """
        <style>
        """ + _font_face_block() + """
        :root {
          --surf-paper: #FDF9F2;       /* right panel + card surface */
          --surf-paper0: #F5EFE4;      /* disabled input fill */
          --surf-paper1: #EDE4D2;      /* left brand panel surface */
          --surf-paper3: #6C6455;      /* tertiary / meta text */
          --surf-paper4: #3B362C;      /* high-emphasis text */
          --surf-paper5: #28251F;      /* default body text + ink */
          --surf-shadow: #171512;      /* stamp shadow + default card stroke */
          --surf-accent: #C8361D;      /* primary brand accent */
          --surf-accent-deep: #9D2815; /* logo 'r', destructive */
        }
        /* Hide every default Streamlit chrome element so P1 fills the viewport. */
        header, footer, #MainMenu,
        [data-testid="stToolbar"], [data-testid="stDecoration"],
        [data-testid="stStatusWidget"], [data-testid="stHeader"] {
          display: none !important;
          visibility: hidden !important;
          height: 0 !important;
        }
        .stApp { background: var(--surf-paper); }
        .block-container,
        .main .block-container,
        section.main > div.block-container {
          max-width: 100% !important;
          padding: 0 !important;
        }
        [data-testid="stHorizontalBlock"] { gap: 0 !important; }

        /* Left brand panel */
        .surf-p1-left {
          background: var(--surf-paper1);
          border-right: 1px solid var(--surf-paper5);
          box-sizing: border-box;
          color: var(--surf-paper5);
          min-height: 100vh;
          overflow: hidden;
          padding: clamp(48px, 5vw, 88px);
          position: relative;
        }
        .surf-p1-hero {
          font-family: "Fraunces", Georgia, serif;
          font-style: italic;
          font-variation-settings: "WONK" 1;
          letter-spacing: -0.045em;
          line-height: 0.88;
          margin-top: clamp(20px, 3vh, 56px);
        }
        .surf-p1-hero .line {
          display: block;
          font-weight: 900;
          font-size: clamp(120px, 13vw, 240px);
        }
        .surf-p1-hero .accent {
          color: var(--surf-accent-deep);
          font-style: italic;
        }
        .surf-p1-tagline {
          color: var(--surf-paper5);
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: clamp(14px, 1.05vw, 18px);
          font-weight: 500;
          letter-spacing: 0.06em;
          line-height: 1.65;
          margin-top: clamp(36px, 5vh, 64px);
          max-width: 560px;
          text-transform: uppercase;
        }
        .surf-p1-tagline .accent {
          color: var(--surf-accent);
        }
        .surf-p1-footer {
          bottom: clamp(28px, 4vh, 48px);
          color: var(--surf-paper5);
          display: grid;
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 14px;
          font-weight: 400;
          grid-template-columns: repeat(3, 1fr);
          left: clamp(48px, 5vw, 88px);
          line-height: 1.5;
          position: absolute;
          right: clamp(48px, 5vw, 88px);
        }
        .surf-p1-footer span:nth-child(2) { text-align: center; }
        .surf-p1-footer span:nth-child(3) { text-align: right; }

        /* Right setup panel */
        .st-key-p1_setup_panel {
          align-items: center;
          background: var(--surf-paper);
          box-sizing: border-box;
          display: flex;
          justify-content: center;
          min-height: 100vh;
          padding: clamp(48px, 6vw, 96px);
        }
        /* Streamlit 1.56 wraps `with st.container(border=True):` like
           [stVerticalBlock key=p1_setup_panel] > stLayoutWrapper > stVerticalBlock(bordered).
           The legacy stVerticalBlockBorderWrapper selector is kept for older
           Streamlit versions; the LayoutWrapper path is the live target. */
        .st-key-p1_setup_panel > [data-testid="stLayoutWrapper"] {
          max-width: 552px;
          width: min(552px, calc(100vw - 56px));
        }
        .st-key-p1_setup_panel [data-testid="stVerticalBlockBorderWrapper"],
        .st-key-p1_setup_panel > [data-testid="stLayoutWrapper"] > [data-testid="stVerticalBlock"] {
          background: var(--surf-paper) !important;
          border: 2px solid var(--surf-paper5) !important;
          border-radius: 4px !important;
          box-shadow: 8px 8px 0 var(--surf-shadow) !important;
          color: var(--surf-paper5) !important;
          padding: 36px 38px 32px !important;
        }
        .surf-p1-card-h1 {
          color: var(--surf-paper5);
          font-family: "Fraunces", Georgia, serif;
          font-size: clamp(40px, 4.6vw, 56px);
          font-style: italic;
          font-variation-settings: "WONK" 1;
          font-weight: 900;
          letter-spacing: -0.03em;
          line-height: 0.95;
          margin: 0 0 16px;
        }
        .surf-p1-card-subtitle {
          color: var(--surf-paper4);
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 12px;
          font-weight: 500;
          letter-spacing: 0.12em;
          line-height: 1.45;
          margin: 0 0 22px;
          text-transform: uppercase;
        }
        .surf-p1-field-label {
          color: var(--surf-paper5);
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 11px;
          font-weight: 700;
          letter-spacing: 0.14em;
          margin: 18px 0 6px;
          text-transform: uppercase;
        }
        .surf-p1-field-label:first-of-type { margin-top: 4px; }

        .surf-p1-helper {
          color: var(--surf-paper4);
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 12px;
          font-weight: 400;
          letter-spacing: 0.02em;
          line-height: 1.55;
          margin: 14px 0 22px;
        }
        .surf-p1-helper a {
          color: var(--surf-accent);
          text-decoration: none;
        }
        .surf-p1-helper a:hover { text-decoration: underline; }

        .surf-p1-disclaimer {
          color: var(--surf-paper4);
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 11px;
          font-weight: 400;
          letter-spacing: 0.02em;
          line-height: 1.55;
          margin: 14px 0 0;
        }

        /* Inputs — full-width, single Paper5 border (no double-border from
           Streamlit's default stTextInputRootElement light-gray border). */
        .st-key-p1_setup_panel [data-testid="stTextInput"] label {
          display: none !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] {
          width: 100% !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] > div {
          width: 100% !important;
        }
        /* Streamlit 1.56 wraps the input in stTextInputRootElement (default
           light-gray border) plus an inner div. Reset the outer border so
           only one Paper5 stamp border shows. */
        .st-key-p1_setup_panel [data-testid="stTextInputRootElement"] {
          background: var(--surf-paper) !important;
          border: none !important;
          box-shadow: none !important;
          width: 100% !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] > div > div {
          background: var(--surf-paper) !important;
          border: 1.5px solid var(--surf-paper5) !important;
          border-radius: 3px !important;
          box-shadow: none !important;
          width: 100% !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] input {
          background: transparent !important;
          color: var(--surf-paper5) !important;
          font-family: "JetBrains Mono", ui-monospace, monospace !important;
          font-size: 15px !important;
          font-weight: 400 !important;
          letter-spacing: 0.01em !important;
          min-height: 46px !important;
          padding: 12px 14px !important;
          width: 100% !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] input::placeholder {
          color: rgba(40, 37, 31, 0.34) !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] input:focus {
          outline: none !important;
        }
        /* Reveal button on the password input — clean Paper5 ink, no
           inherited Streamlit hover/focus halo, single left-border separator
           so the eye lives in its own keyed cell at the field's right end. */
        .st-key-p1_setup_panel [data-testid="stTextInput"] button {
          background: transparent !important;
          border: none !important;
          border-left: 1.5px solid var(--surf-paper5) !important;
          border-radius: 0 !important;
          box-shadow: none !important;
          color: var(--surf-paper5) !important;
          height: 100% !important;
          margin: 0 !important;
          padding: 0 12px !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] button:hover {
          background: var(--surf-paper0) !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] button:focus,
        .st-key-p1_setup_panel [data-testid="stTextInput"] button:focus-visible {
          outline: none !important;
          box-shadow: none !important;
        }
        .st-key-p1_setup_panel [data-testid="stTextInput"] button svg {
          fill: var(--surf-paper5) !important;
          color: var(--surf-paper5) !important;
        }

        /* Button row — 12px gap inside the card (overrides outer 0px rule). */
        .st-key-p1_setup_panel [data-testid="stHorizontalBlock"] {
          gap: 12px !important;
        }
        .st-key-p1_setup_panel [data-testid="column"] {
          padding: 0 !important;
        }

        /* Stamped buttons with press animation.

           Resting state: 4px offset stamp shadow.
           Hover: lifts 1px, stamp grows to 5px (subtle).
           Active/pressed: button slides 4px into the shadow, shadow vanishes —
                           the "stamp pressed onto paper" effect. */
        .st-key-p1_setup_panel [data-testid="stButton"] button {
          border-radius: 3px !important;
          font-family: "JetBrains Mono", ui-monospace, monospace !important;
          font-size: 12px !important;
          font-weight: 700 !important;
          height: 50px !important;
          letter-spacing: 0.14em !important;
          margin: 4px 4px 8px 0 !important;
          text-transform: uppercase !important;
          width: calc(100% - 4px) !important;
          transition: transform 0.08s ease-out, box-shadow 0.08s ease-out !important;
          will-change: transform, box-shadow !important;
        }
        /* AI USE — Neutral variant: paper surface, ink border, ink text. */
        .st-key-p1_ai_use button {
          background: var(--surf-paper) !important;
          border: 2px solid var(--surf-paper5) !important;
          box-shadow: 4px 4px 0 var(--surf-shadow) !important;
          color: var(--surf-paper5) !important;
        }
        .st-key-p1_ai_use button:hover {
          background: var(--surf-paper0) !important;
          box-shadow: 5px 5px 0 var(--surf-shadow) !important;
          transform: translate(-1px, -1px) !important;
        }
        .st-key-p1_ai_use button:active {
          background: var(--surf-paper0) !important;
          box-shadow: 0 0 0 var(--surf-shadow) !important;
          transform: translate(4px, 4px) !important;
        }
        /* START SURFING — Primary variant: ink fill, paper text. */
        .st-key-p1_submit button {
          background: var(--surf-paper5) !important;
          border: 2px solid var(--surf-paper5) !important;
          box-shadow: 4px 4px 0 var(--surf-shadow) !important;
          color: var(--surf-paper) !important;
        }
        .st-key-p1_submit button:hover {
          background: var(--surf-paper4) !important;
          box-shadow: 5px 5px 0 var(--surf-shadow) !important;
          transform: translate(-1px, -1px) !important;
        }
        .st-key-p1_submit button:active {
          background: var(--surf-paper5) !important;
          box-shadow: 0 0 0 var(--surf-shadow) !important;
          transform: translate(4px, 4px) !important;
        }
        @media (prefers-reduced-motion: reduce) {
          .st-key-p1_setup_panel [data-testid="stButton"] button,
          .st-key-p1_setup_panel [data-testid="stButton"] button:hover,
          .st-key-p1_setup_panel [data-testid="stButton"] button:active {
            transform: none !important;
            transition: background 0.08s ease-out !important;
          }
        }

        @media (max-width: 900px) {
          [data-testid="stHorizontalBlock"] { display: block !important; }
          .surf-p1-left { min-height: 56vh; }
          .st-key-p1_setup_panel { min-height: auto; padding: 48px 24px; }
        }
        @media (prefers-reduced-motion: reduce) {
          * {
            scroll-behavior: auto !important;
            transition: none !important;
          }
        }
        </style>
        """
    )


# Generates only static brand HTML; it receives no callbacks, reads no session
# state, and cannot expose the typed display name or API key.
def _render_left_panel() -> None:
    st.html(
        """
        <section class="surf-p1-left" aria-label="Surf brand panel">
          <div class="surf-p1-hero" aria-label="surf the curve">
            <span class="line">su<span class="accent">r</span>f</span>
            <span class="line">the</span>
            <span class="line">curve</span>
          </div>
          <p class="surf-p1-tagline">
            Surf turns <span class="accent">your slides</span> into mock exams and
            offers you tailored <span class="accent">study guidance</span>
          </p>
          <div class="surf-p1-footer" aria-label="course footer">
            <span>cs en vf</span>
            <span>2026</span>
            <span>HSG</span>
          </div>
        </section>
        """
    )


# Generates an informational dialog from Markdown; it never validates, saves,
# routes, or receives the typed API key.
def _show_ai_use_dialog() -> None:
    @st.dialog(AI_USE_LABEL)
    def _dialog() -> None:
        st.markdown(_load_ai_use_copy())

    _dialog()


# Receives raw widget values plus injected callbacks; returns True only after
# clean values pass validation, save locally, and navigation is triggered.
def _save_after_validation(
    display_name: str,
    api_key: str,
    *,
    validate_key: Callable[[str], bool],
    save_setup: Callable[[str, str], int],
) -> bool:
    """Validate the typed key, save setup on success, and surface user feedback."""
    # Blocks partial setup rows until both local input and key validation pass.
    clean_name = display_name.strip()
    clean_key = api_key.strip()

    # These guards receive stripped strings and generate visible errors only;
    # they do not call Anthropic or write a partial local setup row.
    if not clean_name:
        st.error(MISSING_NAME_ERROR)
        return False
    if not clean_key:
        st.error(MISSING_KEY_ERROR)
        return False

    # Validation receives only the stripped typed key and generates a boolean;
    # exceptions and False both generate the same invalid-key toast.
    try:
        with st.spinner(VALIDATING_COPY):
            key_is_valid = validate_key(clean_key)
    except Exception:
        st.toast(INVALID_KEY_TOAST)
        return False

    if not key_is_valid:
        st.toast(INVALID_KEY_TOAST)
        return False

    # The save callback receives the cleaned name/key pair and generates the
    # local user setup row; routing happens only after that write succeeds.
    try:
        save_setup(clean_name, clean_key)
    except Exception:
        st.toast(SAVE_FAILURE_TOAST)
        return False

    st.toast(SUCCESS_TOAST)
    st.switch_page(SWITCH_PAGE_PATH)
    return True


# Receives validation/save callbacks; generates the right-side Welcome card,
# captures widget values, and dispatches exactly one branch per button click.
def _render_setup_card(
    *,
    validate_key: Callable[[str], bool],
    save_setup: Callable[[str, str], int],
) -> None:
    with st.container(border=True):
        st.html('<h1 class="surf-p1-card-h1">Welcome!</h1>')
        st.html(
            f'<p class="surf-p1-card-subtitle">{escape(MONO_SUBTITLE)}</p>'
        )

        st.html('<div class="surf-p1-field-label">YOUR NAME</div>')
        display_name = st.text_input(
            "DISPLAY NAME",
            key="p1_display_name",
            placeholder="Type Here",
            label_visibility="collapsed",
            autocomplete="name",
        )

        st.html('<div class="surf-p1-field-label">ANTHROPIC API KEY</div>')
        api_key = st.text_input(
            "ANTHROPIC API KEY",
            key="p1_anthropic_api_key",
            type="password",
            placeholder="••••••••",
            label_visibility="collapsed",
        )

        st.html(
            f"""
            <p class="surf-p1-helper">
              If you don't have one, get an API key
              <a href="{CONSOLE_URL}" target="_blank" rel="noreferrer">from
              console.anthropic.com</a>
            </p>
            """
        )

        # The two buttons generate separate booleans so help and submit cannot
        # run together: AI USE opens copy, START SURFING validates and saves.
        col_ai, col_submit = st.columns(2, gap="small")
        with col_ai:
            ai_use_clicked = st.button(
                AI_USE_LABEL,
                key="p1_ai_use",
                use_container_width=True,
            )
        with col_submit:
            submit_clicked = st.button(
                PRIMARY_LABEL,
                key="p1_submit",
                type="primary",
                use_container_width=True,
            )

        st.html(f'<p class="surf-p1-disclaimer">{escape(HELPER_COPY)}</p>')

    if ai_use_clicked:
        _show_ai_use_dialog()
        return

    if submit_clicked:
        _save_after_validation(
            display_name,
            api_key,
            validate_key=validate_key,
            save_setup=save_setup,
        )


# Public entry point for ``views/signup.py``. It receives injectable callbacks
# for tests, generates the two-column layout, and passes the callbacks downward.
def render_signup_flow(
    *,
    validate_key: Callable[[str], bool] = validate_anthropic_key,
    save_setup: Callable[[str, str], int] = upsert_user_setup,
) -> None:
    """Render P1 and persist local setup only after typed-key validation."""
    # Injects callbacks for tests while keeping the live signup path unchanged.
    _render_styles()
    left, right = st.columns([1, 1], gap="small")
    with left:
        _render_left_panel()
    with right:
        with st.container(key="p1_setup_panel"):
            _render_setup_card(validate_key=validate_key, save_setup=save_setup)


# Export only the page renderer; internal helpers stay private to this module.
__all__ = ["render_signup_flow"]
